# Build NDT and run unit tests.
# * Uses docker build-tools container
# * Executes unit tests within travis after build.

dist: trusty
language: ruby
services:
- docker

script:

# Checkout ndt-support repo and replace the ndt submodule with the current ndt
# $TRAVIS_BUILD_DIR and $TRAVIS_COMMIT.
- set -e
# Clone ndt-support without cloning submodules.
- git clone https://github.com/m-lab/ndt-support.git
- cd ndt-support
# Change the ndt-support submodule configuration for ndt to point to the
# $TRAVIS_BUILD_DIR (e.g. the current state of m-lab/ndt being tested by travis).
- git config --file=.gitmodules submodule.ndt.url $TRAVIS_BUILD_DIR
# Sync and update the new ndt-support submodule configuration, which clones all
# submodules (now pulling ndt-support/ndt from $TRAVIS_BUILD_DIR).
- git submodule sync
- git submodule update --init --recursive
# Checkout the current $TRAVIS_COMMIT and set the ndt-support/ndt submodule to
# point to this commit.
- ( cd ndt && git checkout $TRAVIS_COMMIT )
- git commit -a -m 'Local commit of changes so "git submodule update" works'

# Build using the canonical build image and local ndt-support.
- docker run -it -w /root/building
    -v `pwd`:/root/building measurementlab/builder:production-1.0
    bash -c "DISABLE_APPLET_SIGNING=1 ./package/slicebuild.sh iupui_ndt"
- ls -lR build/slicebase-*

#- docker pull gcr.io/mlab-pub/github-m-lab-builder:latest
# Run basic unit tests that don't require web100
#- docker run gcr.io/mlab-pub/github-m-lab-builder /root/ndt_build_and_test.sh

# TODO - collect coverage stats and export to coveralls.

