# Build NDT and run unit tests.
# * Uses docker build-tools container
# * Executes unit tests within travis after build.

dist: trusty
language: ruby
services:
- docker

script:

# Temporarily use the git repo dev branch, instead of the google container registry.
# TODO - update this once the GCR builder is up to date.
- docker build -t build https://github.com/m-lab/builder.git#dev
- docker run build /root/ndt_build_and_test.sh dev

#- docker pull gcr.io/mlab-pub/github-m-lab-builder:latest
# Run basic unit tests that don't require web100
#- docker run gcr.io/mlab-pub/github-m-lab-builder /root/ndt_build_and_test.sh

# TODO - collect coverage stats and export to coveralls.

